// This file has been generated from our REST API schema. Do not edit it manually
// For more details, see the readme at https://github.com/renderinc/public-api-schema

// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package client

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for SandboxPlan.
const (
	SandboxPlanN12gb SandboxPlan = "1-2gb"
	SandboxPlanN24gb SandboxPlan = "2-4gb"
	SandboxPlanN48gb SandboxPlan = "4-8gb"
)

// Defines values for SandboxExecExitType.
const (
	Exit SandboxExecExitType = "exit"
)

// Defines values for SandboxExecOutputType.
const (
	SandboxExecOutputTypeStderr SandboxExecOutputType = "stderr"
	SandboxExecOutputTypeStdout SandboxExecOutputType = "stdout"
)

// Defines values for SandboxExecStartedType.
const (
	Started SandboxExecStartedType = "started"
)

// Defines values for SandboxFileEntryType.
const (
	Directory SandboxFileEntryType = "directory"
	File      SandboxFileEntryType = "file"
	Symlink   SandboxFileEntryType = "symlink"
)

// Defines values for SandboxLifecycleEventType.
const (
	SandboxLifecycleEventTypeCreating   SandboxLifecycleEventType = "creating"
	SandboxLifecycleEventTypeErrored    SandboxLifecycleEventType = "errored"
	SandboxLifecycleEventTypeResuming   SandboxLifecycleEventType = "resuming"
	SandboxLifecycleEventTypeRunning    SandboxLifecycleEventType = "running"
	SandboxLifecycleEventTypeSuspended  SandboxLifecycleEventType = "suspended"
	SandboxLifecycleEventTypeTerminated SandboxLifecycleEventType = "terminated"
)

// Defines values for SandboxLogEventStream.
const (
	SandboxLogEventStreamStderr SandboxLogEventStream = "stderr"
	SandboxLogEventStreamStdout SandboxLogEventStream = "stdout"
)

// Defines values for SandboxNetworkPolicyDefault.
const (
	SandboxNetworkPolicyDefaultAllow SandboxNetworkPolicyDefault = "allow"
	SandboxNetworkPolicyDefaultDeny  SandboxNetworkPolicyDefault = "deny"
)

// Defines values for SandboxNetworkPolicyRuleAction.
const (
	SandboxNetworkPolicyRuleActionAllow SandboxNetworkPolicyRuleAction = "allow"
	SandboxNetworkPolicyRuleActionDeny  SandboxNetworkPolicyRuleAction = "deny"
)

// Defines values for SandboxPOSTPlan.
const (
	SandboxPOSTPlanN12gb SandboxPOSTPlan = "1-2gb"
	SandboxPOSTPlanN24gb SandboxPOSTPlan = "2-4gb"
	SandboxPOSTPlanN48gb SandboxPOSTPlan = "4-8gb"
)

// Defines values for SandboxStatus.
const (
	SandboxStatusCreating   SandboxStatus = "creating"
	SandboxStatusErrored    SandboxStatus = "errored"
	SandboxStatusResuming   SandboxStatus = "resuming"
	SandboxStatusRunning    SandboxStatus = "running"
	SandboxStatusSuspended  SandboxStatus = "suspended"
	SandboxStatusTerminated SandboxStatus = "terminated"
)

// Sandbox defines model for sandbox.
type Sandbox struct {
	// Base Render base image used, or null if a custom image is specified.
	Base      *string   `json:"base"`
	CreatedAt time.Time `json:"createdAt"`

	// Env Inline environment variables. Secret values are redacted.
	Env map[string]string `json:"env"`

	// EnvGroup Attached environment group name or ID, or null.
	EnvGroup *string       `json:"envGroup"`
	Error    *SandboxError `json:"error,omitempty"`
	Id       SandboxId     `json:"id"`

	// IdleTimeout Seconds of inactivity before automatic lifecycle action.
	IdleTimeout int `json:"idleTimeout"`

	// Image OCI image reference, or null if using a Render base image.
	Image         *string              `json:"image"`
	NetworkPolicy SandboxNetworkPolicy `json:"networkPolicy"`

	// Plan Compute plan.
	Plan SandboxPlan `json:"plan"`

	// Region Region the sandbox is running in.
	Region string        `json:"region"`
	Status SandboxStatus `json:"status"`

	// Tags Key-value metadata for filtering and cost tracking.
	Tags map[string]string `json:"tags"`

	// TerminatedAt When the sandbox was terminated, or null.
	TerminatedAt *time.Time `json:"terminatedAt"`

	// Timeout Maximum sandbox lifetime in seconds.
	Timeout int `json:"timeout"`
}

// SandboxPlan Compute plan.
type SandboxPlan string

// SandboxDirectoryListing Directory listing response.
type SandboxDirectoryListing struct {
	Entries []SandboxFileEntry `json:"entries"`

	// Path The absolute path that was listed.
	Path string `json:"path"`
}

// SandboxError defines model for sandboxError.
type SandboxError struct {
	// Code Machine-readable error code.
	Code string `json:"code"`

	// Message Human-readable description. For `setup-failed`, includes the failing command and stderr.
	Message string `json:"message"`
}

// SandboxExecExit Sent when the exec process exits. Server closes the connection after this message.
type SandboxExecExit struct {
	// Code Process exit code.
	Code int                 `json:"code"`
	Type SandboxExecExitType `json:"type"`
}

// SandboxExecExitType defines model for SandboxExecExit.Type.
type SandboxExecExitType string

// SandboxExecMessage Server-sent WebSocket message from an exec session.
type SandboxExecMessage struct {
	union json.RawMessage
}

// SandboxExecOutput A stdout or stderr chunk from an exec session.
type SandboxExecOutput struct {
	// Data Output chunk.
	Data string                `json:"data"`
	Type SandboxExecOutputType `json:"type"`
}

// SandboxExecOutputType defines model for SandboxExecOutput.Type.
type SandboxExecOutputType string

// SandboxExecRequest defines model for sandboxExecRequest.
type SandboxExecRequest struct {
	// Command Command to run. A string is passed to the shell; an array is exec'd directly.
	Command SandboxExecRequest_Command `json:"command"`

	// Detached If `true`, start the process and close the WebSocket immediately. Output streams via `GET /logs`.
	Detached *bool `json:"detached,omitempty"`

	// Env Additional environment variables for this execution.
	Env *map[string]string `json:"env,omitempty"`

	// Workdir Working directory. Defaults to `/` or the image default.
	Workdir *string `json:"workdir,omitempty"`
}

// SandboxExecRequestCommand0 defines model for .
type SandboxExecRequestCommand0 = string

// SandboxExecRequestCommand1 defines model for .
type SandboxExecRequestCommand1 = []string

// SandboxExecRequest_Command Command to run. A string is passed to the shell; an array is exec'd directly.
type SandboxExecRequest_Command struct {
	union json.RawMessage
}

// SandboxExecStarted Sent when the exec session starts. Contains the stable execId.
type SandboxExecStarted struct {
	// ExecId Stable ID for this execution — use to correlate output in the logs stream.
	ExecId string                 `json:"execId"`
	Type   SandboxExecStartedType `json:"type"`
}

// SandboxExecStartedType defines model for SandboxExecStarted.Type.
type SandboxExecStartedType string

// SandboxFileEntry A file or directory entry in a sandbox filesystem listing.
type SandboxFileEntry struct {
	// ModifiedAt Last-modified timestamp.
	ModifiedAt time.Time `json:"modifiedAt"`

	// Name File or directory name (basename, not full path).
	Name string `json:"name"`

	// Size Size in bytes. 0 for directories and symlinks.
	Size int `json:"size"`

	// Target Symlink target path. Present only when type is `symlink`.
	Target *string `json:"target,omitempty"`

	// Type Entry type.
	Type SandboxFileEntryType `json:"type"`
}

// SandboxFileEntryType Entry type.
type SandboxFileEntryType string

// SandboxId defines model for sandboxId.
type SandboxId = string

// SandboxLifecycleEvent A lifecycle event from the sandbox logs stream.
type SandboxLifecycleEvent struct {
	At   time.Time                 `json:"at"`
	Type SandboxLifecycleEventType `json:"type"`
}

// SandboxLifecycleEventType defines model for SandboxLifecycleEvent.Type.
type SandboxLifecycleEventType string

// SandboxLogEvent A log event from the sandbox logs stream.
type SandboxLogEvent struct {
	At time.Time `json:"at"`

	// Data Output chunk.
	Data string `json:"data"`

	// ExecId Groups output by command for the event timeline. Absent for system-level output (container startup, OOM, etc.).
	ExecId *string               `json:"execId,omitempty"`
	Stream SandboxLogEventStream `json:"stream"`
}

// SandboxLogEventStream defines model for SandboxLogEvent.Stream.
type SandboxLogEventStream string

// SandboxNetworkPolicy defines model for sandboxNetworkPolicy.
type SandboxNetworkPolicy struct {
	// Default Default action when no rule matches.
	Default SandboxNetworkPolicyDefault `json:"default"`

	// Rules Rules evaluated against outbound traffic. Explicit `deny` always beats explicit
	// `allow` regardless of rule order.
	Rules []SandboxNetworkPolicyRule `json:"rules"`
}

// SandboxNetworkPolicyDefault Default action when no rule matches.
type SandboxNetworkPolicyDefault string

// SandboxNetworkPolicyRule defines model for sandboxNetworkPolicyRule.
type SandboxNetworkPolicyRule struct {
	Action SandboxNetworkPolicyRuleAction `json:"action"`

	// Cidr CIDR block to match outbound traffic against.
	Cidr string `json:"cidr"`
}

// SandboxNetworkPolicyRuleAction defines model for SandboxNetworkPolicyRule.Action.
type SandboxNetworkPolicyRuleAction string

// SandboxPOST defines model for sandboxPOST.
type SandboxPOST struct {
	// Base Render base image: `render/sandbox-python` or `render/sandbox-node`.
	Base *string `json:"base,omitempty"`

	// Env Inline env vars. Merged with env group; inline wins on conflict.
	Env *map[string]string `json:"env,omitempty"`

	// EnvGroup Render environment group name or ID. Variables injected at runtime.
	EnvGroup *string `json:"envGroup,omitempty"`

	// Files Seed files. Keys are absolute paths, values are file contents. Written after `setup` completes.
	Files *map[string]string `json:"files,omitempty"`

	// IdleTimeout Seconds of inactivity before the sandbox is suspended.
	IdleTimeout *int `json:"idleTimeout,omitempty"`

	// Image Docker/OCI image reference. Overrides `base`.
	Image         *string               `json:"image,omitempty"`
	NetworkPolicy *SandboxNetworkPolicy `json:"networkPolicy,omitempty"`

	// Plan Compute plan.
	Plan *SandboxPOSTPlan `json:"plan,omitempty"`

	// Region Render region. Defaults to the workspace default.
	Region *string `json:"region,omitempty"`

	// Setup Shell commands run sequentially after boot, before the sandbox is marked ready.
	Setup *[]string `json:"setup,omitempty"`

	// Tags Key-value metadata for filtering and cost tracking.
	Tags *map[string]string `json:"tags,omitempty"`

	// Timeout Maximum sandbox lifetime in seconds. Sandbox is terminated when reached.
	Timeout *int `json:"timeout,omitempty"`
}

// SandboxPOSTPlan Compute plan.
type SandboxPOSTPlan string

// SandboxStatus defines model for sandboxStatus.
type SandboxStatus string

// AsSandboxExecStarted returns the union data inside the SandboxExecMessage as a SandboxExecStarted
func (t SandboxExecMessage) AsSandboxExecStarted() (SandboxExecStarted, error) {
	var body SandboxExecStarted
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSandboxExecStarted overwrites any union data inside the SandboxExecMessage as the provided SandboxExecStarted
func (t *SandboxExecMessage) FromSandboxExecStarted(v SandboxExecStarted) error {
	v.Type = "started"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSandboxExecStarted performs a merge with any union data inside the SandboxExecMessage, using the provided SandboxExecStarted
func (t *SandboxExecMessage) MergeSandboxExecStarted(v SandboxExecStarted) error {
	v.Type = "started"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSandboxExecOutput returns the union data inside the SandboxExecMessage as a SandboxExecOutput
func (t SandboxExecMessage) AsSandboxExecOutput() (SandboxExecOutput, error) {
	var body SandboxExecOutput
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSandboxExecOutput overwrites any union data inside the SandboxExecMessage as the provided SandboxExecOutput
func (t *SandboxExecMessage) FromSandboxExecOutput(v SandboxExecOutput) error {
	v.Type = "stderr"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSandboxExecOutput performs a merge with any union data inside the SandboxExecMessage, using the provided SandboxExecOutput
func (t *SandboxExecMessage) MergeSandboxExecOutput(v SandboxExecOutput) error {
	v.Type = "stderr"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSandboxExecExit returns the union data inside the SandboxExecMessage as a SandboxExecExit
func (t SandboxExecMessage) AsSandboxExecExit() (SandboxExecExit, error) {
	var body SandboxExecExit
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSandboxExecExit overwrites any union data inside the SandboxExecMessage as the provided SandboxExecExit
func (t *SandboxExecMessage) FromSandboxExecExit(v SandboxExecExit) error {
	v.Type = "exit"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSandboxExecExit performs a merge with any union data inside the SandboxExecMessage, using the provided SandboxExecExit
func (t *SandboxExecMessage) MergeSandboxExecExit(v SandboxExecExit) error {
	v.Type = "exit"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SandboxExecMessage) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SandboxExecMessage) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "exit":
		return t.AsSandboxExecExit()
	case "started":
		return t.AsSandboxExecStarted()
	case "stderr":
		return t.AsSandboxExecOutput()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SandboxExecMessage) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SandboxExecMessage) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSandboxExecRequestCommand0 returns the union data inside the SandboxExecRequest_Command as a SandboxExecRequestCommand0
func (t SandboxExecRequest_Command) AsSandboxExecRequestCommand0() (SandboxExecRequestCommand0, error) {
	var body SandboxExecRequestCommand0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSandboxExecRequestCommand0 overwrites any union data inside the SandboxExecRequest_Command as the provided SandboxExecRequestCommand0
func (t *SandboxExecRequest_Command) FromSandboxExecRequestCommand0(v SandboxExecRequestCommand0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSandboxExecRequestCommand0 performs a merge with any union data inside the SandboxExecRequest_Command, using the provided SandboxExecRequestCommand0
func (t *SandboxExecRequest_Command) MergeSandboxExecRequestCommand0(v SandboxExecRequestCommand0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSandboxExecRequestCommand1 returns the union data inside the SandboxExecRequest_Command as a SandboxExecRequestCommand1
func (t SandboxExecRequest_Command) AsSandboxExecRequestCommand1() (SandboxExecRequestCommand1, error) {
	var body SandboxExecRequestCommand1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSandboxExecRequestCommand1 overwrites any union data inside the SandboxExecRequest_Command as the provided SandboxExecRequestCommand1
func (t *SandboxExecRequest_Command) FromSandboxExecRequestCommand1(v SandboxExecRequestCommand1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSandboxExecRequestCommand1 performs a merge with any union data inside the SandboxExecRequest_Command, using the provided SandboxExecRequestCommand1
func (t *SandboxExecRequest_Command) MergeSandboxExecRequestCommand1(v SandboxExecRequestCommand1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SandboxExecRequest_Command) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SandboxExecRequest_Command) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
