// This file has been generated from our REST API schema. Do not edit it manually
// For more details, see public-api-schema/README.md.

// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package client

import (
	"time"
)

// Defines values for SandboxFileEntryType.
const (
	Directory SandboxFileEntryType = "directory"
	File      SandboxFileEntryType = "file"
	Symlink   SandboxFileEntryType = "symlink"
)

// Defines values for SandboxLifecycleEventType.
const (
	SandboxLifecycleEventTypeCreating   SandboxLifecycleEventType = "creating"
	SandboxLifecycleEventTypeErrored    SandboxLifecycleEventType = "errored"
	SandboxLifecycleEventTypeResuming   SandboxLifecycleEventType = "resuming"
	SandboxLifecycleEventTypeRunning    SandboxLifecycleEventType = "running"
	SandboxLifecycleEventTypeSuspended  SandboxLifecycleEventType = "suspended"
	SandboxLifecycleEventTypeTerminated SandboxLifecycleEventType = "terminated"
)

// Defines values for SandboxLogEventStream.
const (
	Stderr SandboxLogEventStream = "stderr"
	Stdout SandboxLogEventStream = "stdout"
)

// Defines values for SandboxNetworkPolicyDefault.
const (
	AllowAll SandboxNetworkPolicyDefault = "allow-all"
	DenyAll  SandboxNetworkPolicyDefault = "deny-all"
)

// Defines values for SandboxPlan.
const (
	Pro      SandboxPlan = "pro"
	Standard SandboxPlan = "standard"
	Starter  SandboxPlan = "starter"
)

// Defines values for SandboxStatus.
const (
	SandboxStatusCreating   SandboxStatus = "creating"
	SandboxStatusErrored    SandboxStatus = "errored"
	SandboxStatusResuming   SandboxStatus = "resuming"
	SandboxStatusRunning    SandboxStatus = "running"
	SandboxStatusSuspended  SandboxStatus = "suspended"
	SandboxStatusTerminated SandboxStatus = "terminated"
)

// Sandbox defines model for sandbox.
type Sandbox struct {
	CreatedAt     time.Time            `json:"createdAt"`
	Id            SandboxId            `json:"id"`
	NetworkPolicy SandboxNetworkPolicy `json:"networkPolicy"`

	// Plan Compute plan. Sizing matches Workflow plans of the same name.
	Plan SandboxPlan `json:"plan"`

	// Region Region the sandbox is running in.
	Region string        `json:"region"`
	Status SandboxStatus `json:"status"`

	// TerminatedAt When the sandbox was terminated, or null.
	TerminatedAt *time.Time `json:"terminatedAt"`

	// TimeoutSeconds Maximum sandbox lifetime in seconds.
	TimeoutSeconds int `json:"timeoutSeconds"`
}

// SandboxDirectoryListing Directory listing response.
type SandboxDirectoryListing struct {
	Entries []SandboxFileEntry `json:"entries"`

	// Path The absolute path that was listed.
	Path string `json:"path"`
}

// SandboxExecSyncRequest Body of the synchronous exec endpoint.
type SandboxExecSyncRequest struct {
	// Command Bash command to run. Passed to `bash -c` in the sandbox.
	Command string `json:"command"`
}

// SandboxExecSyncResponse Response from the synchronous exec endpoint. Returned after the command exits.
type SandboxExecSyncResponse struct {
	// ExitCode Process exit code.
	ExitCode int `json:"exitCode"`

	// Stderr Captured stderr.
	Stderr string `json:"stderr"`

	// Stdout Captured stdout.
	Stdout string `json:"stdout"`
}

// SandboxFileEntry A file or directory entry in a sandbox filesystem listing.
type SandboxFileEntry struct {
	// ModifiedAt Last-modified timestamp.
	ModifiedAt time.Time `json:"modifiedAt"`

	// Name File or directory name (basename, not full path).
	Name string `json:"name"`

	// Size Size in bytes. 0 for directories and symlinks.
	Size int `json:"size"`

	// Target Symlink target path. Present only when type is `symlink`.
	Target *string `json:"target,omitempty"`

	// Type Entry type.
	Type SandboxFileEntryType `json:"type"`
}

// SandboxFileEntryType Entry type.
type SandboxFileEntryType string

// SandboxId defines model for sandboxId.
type SandboxId = string

// SandboxLifecycleEvent A lifecycle event from the sandbox logs stream.
type SandboxLifecycleEvent struct {
	At   time.Time                 `json:"at"`
	Type SandboxLifecycleEventType `json:"type"`
}

// SandboxLifecycleEventType defines model for SandboxLifecycleEvent.Type.
type SandboxLifecycleEventType string

// SandboxLogEvent A log event from the sandbox logs stream.
type SandboxLogEvent struct {
	At time.Time `json:"at"`

	// Data Output chunk.
	Data string `json:"data"`

	// ExecId Groups output by command for the event timeline. Absent for system-level output (container startup, OOM, etc.).
	ExecId *string               `json:"execId,omitempty"`
	Stream SandboxLogEventStream `json:"stream"`
}

// SandboxLogEventStream defines model for SandboxLogEvent.Stream.
type SandboxLogEventStream string

// SandboxNetworkPolicy defines model for sandboxNetworkPolicy.
type SandboxNetworkPolicy struct {
	// Default Default action for outbound traffic.
	Default SandboxNetworkPolicyDefault `json:"default"`
}

// SandboxNetworkPolicyDefault Default action for outbound traffic.
type SandboxNetworkPolicyDefault string

// SandboxPOST defines model for sandboxPOST.
type SandboxPOST struct {
	NetworkPolicy *SandboxNetworkPolicy `json:"networkPolicy,omitempty"`

	// OwnerId The ID of the workspace the sandbox belongs to.
	OwnerId string       `json:"ownerId"`
	Plan    *SandboxPlan `json:"plan,omitempty"`

	// Region Render region. Defaults to the workspace default.
	Region *string `json:"region,omitempty"`

	// TimeoutSeconds Maximum sandbox lifetime in seconds. Sandbox is terminated when reached.
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty"`
}

// SandboxPlan Compute plan. Sizing matches Workflow plans of the same name.
type SandboxPlan string

// SandboxStatus defines model for sandboxStatus.
type SandboxStatus string
