// This file has been generated from our REST API schema. Do not edit it manually
// For more details, see the readme at https://github.com/renderinc/public-api-schema

// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package client

import (
	"time"
)

// GetBlobOutput defines model for getBlobOutput.
type GetBlobOutput struct {
	// ExpiresAt The time at which the presigned URL expires (ISO 8601 format)
	ExpiresAt time.Time `json:"expiresAt"`

	// Url Presigned URL for downloading the blob
	Url string `json:"url"`
}

// PutBlobInput defines model for putBlobInput.
type PutBlobInput struct {
	// SizeBytes The size of the blob in bytes.
	SizeBytes int64 `json:"sizeBytes"`
}

// PutBlobOutput defines model for putBlobOutput.
type PutBlobOutput struct {
	// ExpiresAt The time at which the presigned URL expires (ISO 8601 format)
	ExpiresAt time.Time `json:"expiresAt"`

	// MaxSizeBytes The maximum size of the blob in bytes
	MaxSizeBytes int64 `json:"maxSizeBytes"`

	// Url Presigned URL for uploading the blob
	Url string `json:"url"`
}

// BlobKeyPathParam defines model for blobKeyPathParam.
type BlobKeyPathParam = string
