// This file has been generated from our REST API schema. Do not edit it manually
// For more details, see public-api-schema/README.md.

// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

// Defines values for CliTelemetryEventPOSTInputCompletionKind.
const (
	DiscoveryError  CliTelemetryEventPOSTInputCompletionKind = "discovery_error"
	ExecutionError  CliTelemetryEventPOSTInputCompletionKind = "execution_error"
	ExplicitExit    CliTelemetryEventPOSTInputCompletionKind = "explicit_exit"
	Help            CliTelemetryEventPOSTInputCompletionKind = "help"
	SetupError      CliTelemetryEventPOSTInputCompletionKind = "setup_error"
	Success         CliTelemetryEventPOSTInputCompletionKind = "success"
	ValidationError CliTelemetryEventPOSTInputCompletionKind = "validation_error"
	Version         CliTelemetryEventPOSTInputCompletionKind = "version"
)

// Valid indicates whether the value is a known member of the CliTelemetryEventPOSTInputCompletionKind enum.
func (e CliTelemetryEventPOSTInputCompletionKind) Valid() bool {
	switch e {
	case DiscoveryError:
		return true
	case ExecutionError:
		return true
	case ExplicitExit:
		return true
	case Help:
		return true
	case SetupError:
		return true
	case Success:
		return true
	case ValidationError:
		return true
	case Version:
		return true
	default:
		return false
	}
}

// CliTelemetryEventPOSTInput defines model for cliTelemetryEventPOSTInput.
type CliTelemetryEventPOSTInput struct {
	// AgentSignals Raw allow-listed AI coding agent environment variable names that were active (e.g., CLAUDECODE, CURSOR)
	AgentSignals []string `json:"agent_signals"`

	// Arch CPU architecture the CLI was run on (e.g. "amd64", "arm64")
	Arch string `json:"arch"`

	// CiSignals Raw allow-listed CI environment variable names that were active (e.g., CI, GITHUB_ACTIONS, GITLAB_CI)
	CiSignals []string `json:"ci_signals"`

	// CliVersion Version of the render CLI that sent this event
	CliVersion string `json:"cli_version"`

	// Command The CLI command that was invoked, e.g. "services list"
	Command string `json:"command"`

	// CompletionKind How the CLI invocation completed
	CompletionKind CliTelemetryEventPOSTInputCompletionKind `json:"completion_kind"`

	// DurationMs Wall-clock duration of the invocation in milliseconds
	DurationMs int64 `json:"duration_ms"`

	// ExitCode Process exit code of the invocation
	ExitCode int `json:"exit_code"`

	// InstallationId Stable random installation UUID generated and stored by the CLI
	InstallationId string `json:"installation_id"`

	// IsStderrTty Whether stderr was attached to a TTY at invocation startup
	IsStderrTty bool `json:"is_stderr_tty"`

	// IsStdinTty Whether stdin was attached to a TTY at invocation startup
	IsStdinTty bool `json:"is_stdin_tty"`

	// IsStdoutTty Whether stdout was attached to a TTY at invocation startup
	IsStdoutTty bool `json:"is_stdout_tty"`

	// IsTermDumb Whether the TERM environment variable was set to "dumb" at invocation startup
	IsTermDumb bool `json:"is_term_dumb"`

	// LaunchedFullScreenTui True if the CLI launched a full-, alt-screen TUI program. (false = did not. null = event did not include this data)
	LaunchedFullScreenTui *bool `json:"launched_full_screen_tui,omitempty"`

	// Os Operating system the CLI was run on (e.g. "darwin", "linux", "windows")
	Os string `json:"os"`

	// OutputFormat Output mode selected for the CLI invocation (i.e., interactive, text, json, yaml)
	OutputFormat string `json:"output_format"`

	// StartedAt RFC3339 UTC timestamp of when the CLI command started (client-side clock)
	StartedAt string `json:"started_at"`
}

// CliTelemetryEventPOSTInputCompletionKind How the CLI invocation completed
type CliTelemetryEventPOSTInputCompletionKind string
