// This file has been generated from our REST API schema. Do not edit it manually
// For more details, see public-api-schema/README.md.

// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package client

// Defines values for CliTelemetryEventPOSTInputCompletionKind.
const (
	DiscoveryError  CliTelemetryEventPOSTInputCompletionKind = "discovery_error"
	ExecutionError  CliTelemetryEventPOSTInputCompletionKind = "execution_error"
	ExplicitExit    CliTelemetryEventPOSTInputCompletionKind = "explicit_exit"
	Help            CliTelemetryEventPOSTInputCompletionKind = "help"
	SetupError      CliTelemetryEventPOSTInputCompletionKind = "setup_error"
	Success         CliTelemetryEventPOSTInputCompletionKind = "success"
	ValidationError CliTelemetryEventPOSTInputCompletionKind = "validation_error"
	Version         CliTelemetryEventPOSTInputCompletionKind = "version"
)

// Valid indicates whether the value is a known member of the CliTelemetryEventPOSTInputCompletionKind enum.
func (e CliTelemetryEventPOSTInputCompletionKind) Valid() bool {
	switch e {
	case DiscoveryError:
		return true
	case ExecutionError:
		return true
	case ExplicitExit:
		return true
	case Help:
		return true
	case SetupError:
		return true
	case Success:
		return true
	case ValidationError:
		return true
	case Version:
		return true
	default:
		return false
	}
}

// CliTelemetryEventPOSTInput defines model for cliTelemetryEventPOSTInput.
type CliTelemetryEventPOSTInput struct {
	// Arch CPU architecture the CLI was run on (e.g. "amd64", "arm64")
	Arch string `json:"arch"`

	// CliVersion Version of the render CLI that sent this event
	CliVersion string `json:"cli_version"`

	// Command The CLI command that was invoked, e.g. "services list"
	Command string `json:"command"`

	// CompletionKind How the CLI invocation completed
	CompletionKind CliTelemetryEventPOSTInputCompletionKind `json:"completion_kind"`

	// DurationMs Wall-clock duration of the invocation in milliseconds
	DurationMs int64 `json:"duration_ms"`

	// ExitCode Process exit code of the invocation
	ExitCode int `json:"exit_code"`

	// Os Operating system the CLI was run on (e.g. "darwin", "linux", "windows")
	Os string `json:"os"`
}

// CliTelemetryEventPOSTInputCompletionKind How the CLI invocation completed
type CliTelemetryEventPOSTInputCompletionKind string
